server:
  port: 9103

spring:
  application:
    name: dynamic-tp-adapter-rabbitmq-demo
  profiles:
    active: dev

  rabbitmq:
    host: ${rabbitmq:127.0.0.1}
    port: ${port:5672}
    username: admin
    password: admin

  dynamic:
    tp:
      enabled: true
      enabledBanner: true           # 是否开启banner打印，默认true
      enabledCollect: true          # 是否开启监控指标采集，默认false
      collectorTypes: internal_logging       # 监控数据采集器类型（logging | micrometer | internal_logging），默认micrometer
      monitorInterval: 5